import { useMemo } from "react";
import { Sparkles } from "lucide-react";
import { format } from "date-fns";
import { useAiBriefing, useAllGoals, usePortfolioPageDaily } from "@/lib/hooks";
import { buildBriefingSummary, type GoalWithProjection } from "@/lib/briefing";
import { projectGoal } from "@/lib/forecast";
import { computePortfolioDecay } from "@/lib/series";
import type { InsightsWithSites } from "@/lib/api";
import { usePrivacyMode } from "@/lib/privacy";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/alert";
import { Spinner } from "@/components/ui/spinner";

/**
 * On-demand AI briefing. Nothing is sent anywhere until the button is
 * clicked; the server refuses unless the operator has configured an
 * ANTHROPIC_API_KEY Edge Function secret.
 */
export function BriefingCard({
  days,
  insights,
}: {
  days: number;
  insights: InsightsWithSites;
}) {
  const privacy = usePrivacyMode();
  const briefing = useAiBriefing();
  const goalsQuery = useAllGoals();
  const pagesQuery = usePortfolioPageDaily(28);

  const summary = useMemo(() => {
    const today = format(new Date(), "yyyy-MM-dd");
    const decays = computePortfolioDecay(
      pagesQuery.data ?? [],
      insights.sitesWithStatuses,
      today,
    );
    const goals: GoalWithProjection[] = (goalsQuery.data ?? []).map((goal) => {
      const site = insights.sitesWithStatuses.find(
        (s) => s.id === goal.site_id,
      );
      const series =
        goal.metric === "sessions"
          ? insights.raw.analytics
              .filter((r) => r.site_id === goal.site_id)
              .map((r) => ({ date: r.metric_date, value: r.sessions }))
          : insights.raw.search
              .filter(
                (r) => r.site_id === goal.site_id && r.engine === "google",
              )
              .map((r) => ({ date: r.metric_date, value: r.clicks }));
      return {
        goal,
        siteName: site?.name ?? "Unknown site",
        projection: projectGoal(
          series,
          goal.target_value,
          goal.target_date,
          today,
        ),
      };
    });
    return buildBriefingSummary(insights, decays, goals);
  }, [insights, pagesQuery.data, goalsQuery.data]);

  const notConfigured = briefing.data != null && !briefing.data.configured;

  return (
    <Card>
      <CardContent className="space-y-3 p-4">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" aria-hidden />
            <span className="text-sm font-semibold">AI briefing</span>
          </div>
          <Button
            size="sm"
            variant="secondary"
            disabled={briefing.isPending || privacy.enabled}
            title={
              privacy.enabled
                ? "Turn off Hide all data to generate a briefing."
                : undefined
            }
            onClick={() => briefing.mutate({ days, summary })}
          >
            {briefing.isPending ? (
              <>
                <Spinner className="h-3.5 w-3.5" /> Generating…
              </>
            ) : briefing.data?.briefing ? (
              "Regenerate"
            ) : (
              "Generate briefing"
            )}
          </Button>
        </div>

        {briefing.isError && (
          <Alert tone="error">{(briefing.error as Error).message}</Alert>
        )}

        {notConfigured && (
          <Alert tone="info">
            AI briefings are off. Set the <code>ANTHROPIC_API_KEY</code> Edge
            Function secret (and redeploy nothing - it takes effect immediately)
            to enable them. Your data goes only to the Claude API, on demand,
            never automatically.
          </Alert>
        )}

        {briefing.data?.briefing ? (
          <div className="space-y-2 text-sm leading-relaxed">
            {briefing.data.briefing.split(/\n{2,}/).map((paragraph, i) => (
              <p key={i}>{paragraph}</p>
            ))}
            <p className="text-xs text-muted-foreground">
              Generated by {briefing.data.model} from the last {days} days of
              aggregate data.
            </p>
          </div>
        ) : (
          !notConfigured &&
          !briefing.isPending && (
            <p className="text-sm text-muted-foreground">
              A short analyst-style read of the portfolio: what changed, what
              needs attention, and what to do next. Generated on demand from the
              aggregates on this page - never automatically.
            </p>
          )
        )}
      </CardContent>
    </Card>
  );
}
